apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi
  name: fastapi-svc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: fastapi-port
      port: 80
      protocol: TCP
      targetPort: 8000
  selector:
    app: fastapi
  sessionAffinity: None
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fastapi
  name: fastapi
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - image: gcr.io/inbound-hawk-320111/fastapi:latest
          imagePullPolicy: always
          name: fastapi
          ports:
          - containerPort: 80
