#Use the official python image
#FROM tiangolo/uvicorn-gunicorn
FROM python:3.7.3-stretch

#Create and change to the app directory
WORKDIR /app

#Copy application dependency manifests to the container image
COPY . .

#Install production dependences
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install -r requirements.txt

#Run Test with pytest runner
RUN pytest tests-pass/*


#Exposing running port
EXPOSE 8000


#Running app
CMD [ "uvicorn" ,"--host", "0.0.0.0" ,  "main:app",  "--reload" ]
#CMD [ "uvicorn" ,  "main:app",  "--reload" ]
